import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';import {CARNE,PROPRIOS,sale,phone,signature,send} from '../src/core.js';import {store} from '../src/store.js';
const payload=(extra=[])=>({payment:{id:'pedido-ficticio',status:'paid'},customer:{mobile_phone:'(79) 99999-0000'},products:[{id:CARNE},...extra]});
test('carne e combo por IDs, sem depender de título',()=>{assert.equal(sale(payload()).kind,'carne');assert.equal(sale(payload([{id:PROPRIOS}])).kind,'combo');assert.equal(sale(payload([{id:'bump-whatsapp'}])).kind,'carne');});
test('ignora pendente e produto desconhecido',()=>{const p=payload();p.payment.status='pending';assert.equal(sale(p),null);p.payment.status='paid';p.products=[];assert.equal(sale(p),null);});
test('telefone e campos obrigatórios',()=>{assert.equal(phone('(79) 99999-0000'),'5579999990000');assert.equal(phone('+55 79 99999-0000'),'5579999990000');assert.throws(()=>phone('123'));const p=payload();delete p.payment.id;assert.throws(()=>sale(p));});
test('assinatura Meta',()=>{const raw=Buffer.from('{}');const s='sha256='+createHmac('sha256','secret').update(raw).digest('hex');assert.ok(signature(raw,'secret',s));assert.ok(!signature(raw,'other',s));});
test('duplicados, fila e entrega não regridem',()=>{const st=store(':memory:');const r=sale(payload());assert.equal(st.add(r),1);assert.equal(st.add(r),0);const next=st.next();assert.equal(st.next(),undefined);st.finish(next,{state:'accepted',mid:'wamid.test'});st.status({id:'wamid.test',status:'read',timestamp:'123'});st.status({id:'wamid.test',status:'sent',timestamp:'124'});assert.equal(st.list()[0].state,'read');st.db.close();});
test('modo simulado não chama API',async()=>{assert.equal((await send(sale(payload()),{dry:true},()=>{throw Error('called');})).state,'simulated');});
test('resposta aceita, retry limitado a rejeição explícita, timeout incerto',async()=>{const r=sale(payload());const cfg={dry:false,version:'v00.0',number:'123',token:'test',carne:'carne',combo:'combo'};let captured;const good=await send(r,cfg,async(url,opts)=>{captured=JSON.parse(opts.body);return {ok:true,json:async()=>({messages:[{id:'wamid.x'}]})};});assert.equal(good.state,'accepted');assert.equal(captured.template.name,'carne');assert.equal(captured.biz_opaque_callback_data,r.id);assert.equal((await send(r,cfg,async()=>{throw Error('timeout');})).state,'uncertain');assert.equal((await send(r,cfg,async()=>({status:429,ok:false,json:async()=>({error:{code:4}})}))).state,'retry');assert.equal((await send(r,cfg,async()=>({status:400,ok:false,json:async()=>({error:{code:132001}})}))).state,'failed');});
